### ISSUE TITLE
update for new url structure for vtop

### ISSUE THREAD

**Issue by sudo-vaibhav** [sudonims/vtop-da-deadline#11]
Ever since vtop has been overhauled and the base URLs have been changed, the extension has stopped working and doesn't show the DA deadlines in the main page. Can this be fixed? I would really appreciate it.

**Comment by sudonims** [comment]
Hi @sudo-vaibhav , thanks for the bug... I made a new push [here](https://github.com/sudonims/vtop-da-deadline/commit/ab6a95cc177e8b10135eea16b6b2cd670dec0fef) which should solve the issue. DO check it and let me know, I have no DAs to check it against...

**Comment by sudo-vaibhav** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/53619134/180993851-f4c2cd08-9196-42d1-8092-3d8f45ac6c9d.png">

nope, still doesn't show, the URLs have been changed in vtop so that could be the reason, it contains "content" in URL now
